"""Add Classification table

Revision ID: 356e23d15a13
Revises: 2839bc545e53
Create Date: 2025-07-02 15:41:45.710896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356e23d15a13'
down_revision = '2839bc545e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('zip_filename', sa.String(), nullable=False),
    sa.Column('result_folder', sa.String(), nullable=False),
    sa.Column('download_token', sa.String(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('total_images', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('download_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classifications')
    # ### end Alembic commands ###
