"""Add json_filename to Classification

Revision ID: 7ce68bf9e7aa
Revises: 356e23d15a13
Create Date: 2025-07-02 17:04:37.703604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce68bf9e7aa'
down_revision = '356e23d15a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.drop_column('json_filename')

    # ### end Alembic commands ###
