"""empty message

Revision ID: ff90bb6e5db2
Revises: 7ce68bf9e7aa
Create Date: 2025-07-07 14:37:58.316128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff90bb6e5db2'
down_revision = '7ce68bf9e7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.drop_column('upload_filename')

    # ### end Alembic commands ###
